name: Build
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        gradle-version:
          - 7.6 # the latest release that is tested with Kotlin 1.3.72 through 1.7.10
          - 7.3 # the first release that is tested with Kotlin 1.5.31
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ matrix.gradle-version }}
          arguments: build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: build/reports
